In [1]:
#!pip install gym

In [2]:
import gym

In [3]:
env = gym.make('Acrobot-v1')

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


Main API methods of `env`

*   `step`  
*   `reset`  
*   `render`  
*   `close`  
*   `seed`  


And set the following attributes:

* `action_space`: The Space object corresponding to valid actions
* `observation_space`: The Space object corresponding to valid observations
* `reward_range`: A tuple corresponding to the min and max possible rewards

array([ 0.99844442,  0.05575604,  0.9973611 , -0.07260046,  0.09580993,
       -0.05133606])

**STATE:**
 
The state consists of the sin() and cos() of the two rotational joint
angles and the joint angular velocities :

[cos(theta1) sin(theta1) cos(theta2) sin(theta2) thetaDot1 thetaDot2].

For the first link, an angle of 0 corresponds to the link pointing downwards.
The angle of the second link is relative to the angle of the first link.
An angle of 0 corresponds to having the same angle between the two links.
A state of [1, 0, 1, 0, ..., ...] means that both links point downwards

In [4]:
env.reset()
for t in range(1000): 
    env.render()
    if t % 3 == 0 : 
        action = env.action_space.sample()
    elif t % 3 == 1: 
        action = 2
    else:
        action = env.action_space.sample()
    #action = env.action_space.sample()
    obs,rwd,done,info = env.step(action)
    
    print(obs)
    if done:
        print("Episode finished after {} timesteps".format(t+1))
        break
    

[ 0.99965388  0.02630828  0.99769248 -0.06789482  0.10226809 -0.22058107]
[ 0.99960938  0.02794791  0.99780892 -0.06616161 -0.08586647  0.23737174]
[ 0.99997425  0.00717596  0.99993333 -0.01154729 -0.11594543  0.29657046]
[ 0.99999689 -0.00249517  0.99992174  0.01251067  0.02172305 -0.0612014 ]
[ 0.99993797 -0.01113798  0.99943536  0.03360012 -0.10553819  0.26678391]
[ 0.99957788 -0.0290528   0.99680755  0.07984181 -0.06865113  0.18581919]
[ 0.99931595 -0.0369815   0.99454866  0.1042735  -0.00842471  0.0543187 ]
[ 0.99897134 -0.04534592  0.99090546  0.13455994 -0.07250661  0.24392946]
[ 0.99794209 -0.06412171  0.98052137  0.19641242 -0.10965743  0.36946379]
[ 0.99818391 -0.0602402   0.97837201  0.20685313  0.14759862 -0.26321821]
[ 0.99940865 -0.03438524  0.98630124  0.16495411  0.10474131 -0.1520436 ]
[ 0.99978954 -0.02051538  0.98861591  0.15046121  0.03084667  0.00975977]
[ 0.9999926   0.00384714  0.99484309  0.10142594  0.20624201 -0.4917298 ]
[ 0.99952161  0.03092825  0.99948419  

[ 0.97164253  0.23645462  0.88899866 -0.45790979 -1.14075825  1.18943297]
[ 0.99999401 -0.00346138  0.9775373  -0.21076248 -1.22447269  1.36008856]
[ 0.96804493 -0.25077682  0.99503205  0.09955511 -1.21478722  1.66197241]
[ 0.89376308 -0.44853936  0.91628801  0.40052001 -0.85224297  1.38061477]
[ 0.85038762 -0.52615673  0.84588133  0.53337114 -0.02194641  0.10343763]
[ 0.87829364 -0.47812162  0.86894078  0.49491607  0.56697674 -0.54192837]
[ 0.94407108 -0.32974201  0.93755963  0.34782457  1.02435072 -1.04194795]
[ 0.99560953 -0.09360374  0.99584975  0.09101245  1.34262216 -1.51740917]
[ 0.98698729  0.16079828  0.98441889 -0.17583927  1.14927179 -1.07099813]
[ 0.9367138   0.35009606  0.94222962 -0.33496767  0.77030773 -0.52456839]
[ 0.89749455  0.44102554  0.93133474 -0.36416425  0.20214869  0.22624382]
[ 0.91194457  0.41031342  0.97627246 -0.21654579 -0.53184752  1.29204879]
[ 0.96071462  0.27753813  0.9985396   0.05402473 -0.84722101  1.36323364]
[ 0.9961426   0.08774922  0.94577539  

[ 0.82965786  0.55827218  0.8884056  -0.45905935 -0.20901392  0.94340153]
[ 0.88864041  0.45860465  0.98020624 -0.1979791  -0.92243212  1.78101348]
[ 0.97405349  0.22631792  0.97223072  0.2340244  -1.49388778  2.45218682]
[ 0.99602707 -0.08905099  0.75107798  0.6602135  -1.60369956  2.25850411]
[ 0.93485278 -0.3550356   0.50879261  0.86088912 -1.08690704  0.85430215]
[ 0.87386313 -0.48617201  0.49493312  0.86893107 -0.32921377 -0.70537922]
[ 0.87344475 -0.48692327  0.68732431  0.72635067  0.32275767 -1.67712947]
[ 0.93183867 -0.36287283  0.9342078   0.35672928  1.01683885 -2.73695543]
[ 0.9936067  -0.11289694  0.96474847 -0.2631737   1.4781127  -3.39548787]
[ 0.98772875  0.15617911  0.65953142 -0.751677    1.16225603 -2.3345331 ]
[ 0.94360191  0.33108223  0.38271512 -0.92386641  0.62246307 -0.91863345]
[ 0.91738983  0.39798983  0.32335727 -0.94627696  0.08375196  0.2909403 ]
[ 0.93683946  0.34975966  0.51281362 -0.85849996 -0.60658399  1.80178848]
[ 0.98359116  0.18041184  0.84898932 -

[ 0.98649115 -0.16381456  0.94310609  0.33249197  0.16669076  0.14946064]
[ 0.99561304 -0.09356641  0.95930924  0.28235755  0.52595797 -0.65787304]
[ 0.99973714  0.02292721  0.99230183  0.12384295  0.61199815 -0.91758212]
[ 0.99214748  0.1250735   0.99967012 -0.02568376  0.38742569 -0.53892547]
[ 0.98556638  0.16928944  0.99689264 -0.07877218  0.04954232  0.02216151]
[ 0.98759953  0.15699419  0.99871674 -0.05064455 -0.1705657   0.25266003]
[ 0.99577157  0.09186391  0.99870225  0.0509295  -0.46918305  0.73519813]
[ 0.99997409 -0.00719807  0.9814656   0.19163838 -0.49830742  0.64371803]
[ 0.9952444  -0.0974094   0.95730589  0.28907685 -0.38453437  0.33085547]
[ 0.9860984  -0.16616244  0.93945523  0.34267166 -0.29381988  0.21491443]
[  9.80676243e-01  -1.95637691e-01   9.42920468e-01   3.33018003e-01
  -3.63147647e-04  -3.19496570e-01]
[ 0.98809735 -0.15382989  0.98165214  0.19068058  0.41307199 -1.12818849]
[ 0.99772859 -0.06736216  0.99972573 -0.02341914  0.43213292 -0.97272753]
[ 0.999

[ 0.9996648  -0.02588985  0.96608577 -0.25822137  0.59258648 -0.61861318]
[ 0.99737753  0.07237449  0.94967865 -0.3132259   0.36943689  0.06774262]
[ 0.98997707  0.1412282   0.95606692 -0.29314851  0.30992713  0.14961816]
[ 0.98634077  0.1647176   0.98212882 -0.18820991 -0.07426234  0.91811044]
[ 0.99336332  0.11501877  0.99839241  0.05667968 -0.40832703  1.4902647 ]
[ 0.99921223  0.03968515  0.9518579   0.30653962 -0.32508699  1.00495157]
[ 0.9994475  -0.03323698  0.87330179  0.48717962 -0.38459304  0.92576465]
[ 0.99434815 -0.10616855  0.78616701  0.61801411 -0.3299873   0.61662102]
[ 0.99083664 -0.13506576  0.77574484  0.6310467   0.04476871 -0.45484   ]
[ 0.9961135  -0.08807892  0.88377227  0.46791727  0.42024614 -1.48076208]
[  9.99999263e-01  -1.21424914e-03   9.84332345e-01   1.76323100e-01
   4.21122825e-01  -1.54890860e+00]
[ 0.99553177  0.09442716  0.98521589 -0.17131737  0.50217703 -1.8636096 ]
[ 0.98302027  0.18349699  0.86140824 -0.50791323  0.36617878 -1.66616609]
[ 0.978

In [60]:
env.s

AttributeError: 'TimeLimit' object has no attribute 'state'

In [62]:
results

(array([-0.41987682,  0.9075811 ,  0.94445152, -0.32865076, -1.51136886,
        -0.06605537]), -1.0, True, {})

In [42]:
obresults

(array([-0.41987682,  0.9075811 ,  0.94445152, -0.32865076, -1.51136886,
        -0.06605537]), -1.0, True, {})